### **Practice Problem 1:**


In [1]:
import numpy as np

matrix_a = np.random.rand(4, 4)

if np.allclose(matrix_a, matrix_a.T):
    print("\nThe matrix is symmetric.")
else:
    print("\nThe matrix is not symmetric.")


The matrix is not symmetric.


### **Practice Problem 2:**

In [2]:
import numpy as np

matrix_a = np.eye(5)

trace = np.trace(matrix_a)
print("The trace of the matrix is:", trace)

The trace of the matrix is: 5.0


### **Practice Problem 3:**

In [3]:
import numpy as np

matrix_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])

inverse = np.linalg.inv(matrix_a)
determinant = np.linalg.det(matrix_a)
print("The determinant of the matrix is:", determinant)

The determinant of the matrix is: -2.9999999999999996


### **Practice Problem 4: Application in Computer Science**

In [5]:
import numpy as np

matrix_a = np.random.rand(3, 33)
print("Original Matrix:")
print(matrix_a)

transpose = np.transpose(matrix_a)
print("\nTranspose of the Matrix:")
print(transpose)
print("\nDeterminant of the Matrix:")
print("The determinant is not defined for non-square matrices.")

Original Matrix:
[[0.87616825 0.18623343 0.41773071 0.48368481 0.05586817 0.19123202
  0.50513354 0.66951825 0.82386847 0.01776836 0.86549752 0.36098575
  0.91861396 0.8406087  0.66437077 0.29016556 0.1497734  0.93944041
  0.55238816 0.87086997 0.35451345 0.73118293 0.3969481  0.59144421
  0.85489001 0.44161756 0.8017143  0.85969936 0.21366229 0.92078154
  0.14414814 0.99231396 0.67487852]
 [0.63349178 0.47502924 0.82080964 0.85114225 0.15783456 0.94684437
  0.68509873 0.27469406 0.45877142 0.34359951 0.19098954 0.49057165
  0.30107096 0.41047348 0.41967034 0.26832609 0.21317164 0.12045681
  0.53129557 0.67820756 0.89434087 0.05626458 0.27778098 0.48657656
  0.55947482 0.6859329  0.45134223 0.66541308 0.838497   0.63097399
  0.83029735 0.25980126 0.8453188 ]
 [0.20552402 0.65691229 0.07321022 0.79145271 0.16359375 0.06410505
  0.692163   0.37294799 0.88866607 0.41269792 0.19941758 0.5692788
  0.3073757  0.61483595 0.89845924 0.3797383  0.79886954 0.87984127
  0.97166124 0.42483959 0.60

### **Practice Problem 5: Symmetric Matrices in Machine Learning**

In [6]:
import numpy as np

matrix_a = np.array([[1, 2, 3], [2, 4, 5], [3, 5, 6]])
print("Original Matrix:")
print(matrix_a)

print("\nIs the matrix symmetric?")
print(np.allclose(matrix_a, matrix_a.T))
print("\nIs the matrix equal to its transpose?")
print(np.array_equal(matrix_a, matrix_a.T))
print("\nIs the matrix equal to its transpose (alternative method)?")
print(np.allclose(matrix_a, matrix_a.T))

eigenvalues, eigenvectors = np.linalg.eig(matrix_a)
print("\nEigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

Original Matrix:
[[1 2 3]
 [2 4 5]
 [3 5 6]]

Is the matrix symmetric?
True

Is the matrix equal to its transpose?
True

Is the matrix equal to its transpose (alternative method)?
True

Eigenvalues:
[11.34481428 -0.51572947  0.17091519]

Eigenvectors:
[[-0.32798528 -0.73697623  0.59100905]
 [-0.59100905 -0.32798528 -0.73697623]
 [-0.73697623  0.59100905  0.32798528]]
